### PR TITLE
sdoc/grammar: introduce REFS/RELATIONS/ROLES

### PR DESCRIPTION
**Pull request by stanislaw**

### CODE REVIEW

**Comment by BenGardiner** [comment]
hi @stanislaw , our build started failing on Sept 22nd; I am guessing due to merge of this PR. The first failed build is here https://github.com/nmfta-repo/vcr-experiment/actions/runs/6280339999 where the relevant error message from strictdoc in the logs is `AttributeError: 'GrammarElementFieldString' object has no attribute 'types'`.

I'm not sure how it broke yet but I'm willing to bet it is something weird we were doing in our grammar again.

**Comment by stanislaw** [comment]
Hi @BenGardiner ,

Yes, there is an ongoing migration of 'refs' to 'relations' due to this new ticket: https://github.com/strictdoc-project/strictdoc/issues/1310. I have tried my best to be backwards compatible, but apparently I haven't handled this case gracefully yet. The underlying implementation detail introduced with this and other PRs' work is that the REFS field can no longer contain refs and be of the String type at the same time. 

To fix the issue, I have opened a PR: https://github.com/nmfta-repo/vcr-experiment/pull/55.

Please keep in mind that the migration is at 90%, but there can be some edge cases if you edit the requirements using the web interface.

**Comment by BenGardiner** [comment]
Ok understood I can see there are v good reasons for the migration.

Thank you very much for the PR as well!
