### ISSUE TITLE
strictdoc 0.0.59 dependency lxml 4.9.4 does not install nor build on Windows 11 Enterprise 10.0.22631

### ISSUE THREAD

**Issue by bernhard-tuvsud** [strictdoc-project/strictdoc#1951]
Hello,

I lost my last strictdoc installation and have to install again. Can´t build because lxml 4.9.4 errors out.

The lxml dependency is pinned to 4.*. Current version is 5.3.0. As the required version is old no binary wheel is available and it has to be build. This does not work. I finally this httptools is the culprit. It does not work with python 3.13.

According to pyproject.toml the dependency could be removed.

Command: py.exe -m pip install strictdoc -> see log

Versions:
- py.exe --version -> Python 3.13.0
- Windows: Microsoft Windows 11 Enterprise 10.0.22631 Build 22631
- Visual Studio: Microsoft Visual Studio Community 2022 (64-Bit) - Current Version 17.11.5

Log:
```bash
  Collecting strictdoc
     Using cached strictdoc-0.0.59-py3-none-any.whl
  ...
  ... A lot more messages
  ...
  Building wheel for lxml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lxml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
      <string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Building lxml version 4.9.4.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\builder.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\cssselect.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\doctestcompare.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\ElementInclude.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\sax.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\usedoctest.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\_elementpath.py -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\__init__.py -> build\lib.win-amd64-cpython-313\lxml
      creating build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\__init__.py -> build\lib.win-amd64-cpython-313\lxml\includes
      creating build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\builder.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\clean.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\defs.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\diff.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\formfill.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\html5parser.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\soupparser.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-cpython-313\lxml\html
      copying src\lxml\html\__init__.py -> build\lib.win-amd64-cpython-313\lxml\html
      creating build\lib.win-amd64-cpython-313\lxml\isoschematron
      copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-cpython-313\lxml\isoschematron
      copying src\lxml\etree.h -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\etree_api.h -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\lxml.etree.h -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\etree.pyx -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\objectify.pyx -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\apihelpers.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\classlookup.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\cleanup.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\debug.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\docloader.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\dtd.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\extensions.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\iterparse.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\nsclasses.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\objectpath.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\parser.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\parsertarget.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\proxy.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\public-api.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\readonlytree.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\relaxng.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\saxparser.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\schematron.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\serializer.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xinclude.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xmlerror.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xmlid.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xmlschema.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xpath.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xslt.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\xsltext.pxi -> build\lib.win-amd64-cpython-313\lxml
      copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\config.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-cpython-313\lxml\includes
      copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-cpython-313\lxml\includes
      creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\rng
      copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\rng
      creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
      creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build\temp.win-amd64-cpython-313\Release\src\lxml
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc\lxml\includes -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\include -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc\lxml\etree.c /Fobuild\temp.win-amd64-cpython-313\Release\src\lxml\etree.obj -w
      cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" \x81berschrieben
      etree.c
      C:\Users\noelt-be\AppData\Local\Temp\pip-install-ngjwr_tx\lxml_e53930fcecea495fa518f98d079db454\src\lxml\includes/etree_defs.h(14): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "libxml/xmlversion.h": No such file or directory
      Compile failed: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /TcC:\Users\noelt-be\AppData\Local\Temp\xmlXPathInitcuzqxz__.c /Fo\Users\noelt-be\AppData\Local\Temp\xmlXPathInitcuzqxz__.obj
      xmlXPathInitcuzqxz__.c
      C:\Users\noelt-be\AppData\Local\Temp\xmlXPathInitcuzqxz__.c(1): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "libxml/xpath.h": No such file or directory
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Building wheel for httptools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for httptools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      C:\Users\noelt-be\AppData\Local\Temp\pip-build-env-aonuxf9g\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\httptools
      copying httptools\_version.py -> build\lib.win-amd64-cpython-313\httptools
      copying httptools\__init__.py -> build\lib.win-amd64-cpython-313\httptools
      creating build\lib.win-amd64-cpython-313\httptools\parser
      copying httptools\parser\errors.py -> build\lib.win-amd64-cpython-313\httptools\parser
      copying httptools\parser\__init__.py -> build\lib.win-amd64-cpython-313\httptools\parser
      running egg_info
      writing httptools.egg-info\PKG-INFO
      writing dependency_links to httptools.egg-info\dependency_links.txt
      writing requirements to httptools.egg-info\requires.txt
      writing top-level names to httptools.egg-info\top_level.txt
      reading manifest file 'httptools.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info\SOURCES.txt'
      C:\Users\noelt-be\AppData\Local\Temp\pip-build-env-aonuxf9g\overlay\Lib\site-packages\setuptools\command\build_py.py:218: _Warning: Package 'httptools.parser' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'httptools.parser' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'httptools.parser' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'httptools.parser' to be distributed and are
              already explicitly excluding 'httptools.parser' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      running build_ext
      building 'httptools.parser.parser' extension
      creating build\temp.win-amd64-cpython-313\Release\httptools\parser
      creating build\temp.win-amd64-cpython-313\Release\vendor\llhttp\src
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\noelt-be\AppData\Local\Temp\pip-install-ngjwr_tx\httptools_4657fc8301e4487798d47d57bea2a778\vendor\llhttp\include -IC:\Users\noelt-be\AppData\Local\Temp\pip-install-ngjwr_tx\httptools_4657fc8301e4487798d47d57bea2a778\vendor\llhttp\src -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\include -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-cpython-313\Release\httptools/parser/parser.obj -O2
      parser.c
      httptools/parser/parser.c(849): warning C4996: 'Py_UNICODE': deprecated in 3.13
      httptools/parser/parser.c(850): warning C4996: 'Py_UNICODE': deprecated in 3.13
      httptools/parser/parser.c(3531): warning C4090: "=": Unterschiedliche "const"-Qualifizierer
      httptools/parser/parser.c(9938): error C2198: "int _PyLong_AsByteArray(PyLongObject *,unsigned char *,size_t,int,int,int)": Nicht gen\x81gend Argumente f\x81r Aufruf.
      httptools/parser/parser.c(10134): error C2198: "int _PyLong_AsByteArray(PyLongObject *,unsigned char *,size_t,int,int,int)": Nicht gen\x81gend Argumente f\x81r Aufruf.
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
Successfully built strictdoc
Failed to build lxml httptools
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml, httptools)
```

**Comment by bernhard-tuvsud** [comment]
pip install lxml -U works. 

But now httptools errors out. Seems httptools does not work with Python 3.13.

```bash
Building wheels for collected packages: strictdoc, httptools
  Building editable for strictdoc (pyproject.toml) ... done
  Created wheel for strictdoc: filename=strictdoc-0.0.59-py3-none-any.whl size=3770 sha256=09cb5d34e2e972ee435ba9540a68a93006da419d03abcf8cf5beb585b275ed49
  Stored in directory: C:\Users\noelt-be\AppData\Local\Temp\pip-ephem-wheel-cache-z0keib3u\wheels\81\ee\bc\659b259a21fe3ad0a5065cd4070f8d43c6b571b1698f46083c
  Building wheel for httptools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for httptools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      C:\Users\noelt-be\AppData\Local\Temp\pip-build-env-42km9_ez\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\httptools
      copying httptools\_version.py -> build\lib.win-amd64-cpython-313\httptools
      copying httptools\__init__.py -> build\lib.win-amd64-cpython-313\httptools
      creating build\lib.win-amd64-cpython-313\httptools\parser
      copying httptools\parser\errors.py -> build\lib.win-amd64-cpython-313\httptools\parser
      copying httptools\parser\__init__.py -> build\lib.win-amd64-cpython-313\httptools\parser
      running egg_info
      writing httptools.egg-info\PKG-INFO
      writing dependency_links to httptools.egg-info\dependency_links.txt
      writing requirements to httptools.egg-info\requires.txt
      writing top-level names to httptools.egg-info\top_level.txt
      reading manifest file 'httptools.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info\SOURCES.txt'
      C:\Users\noelt-be\AppData\Local\Temp\pip-build-env-42km9_ez\overlay\Lib\site-packages\setuptools\command\build_py.py:218: _Warning: Package 'httptools.parser' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'httptools.parser' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'httptools.parser' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'httptools.parser' to be distributed and are
              already explicitly excluding 'httptools.parser' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      running build_ext
      building 'httptools.parser.parser' extension
      creating build\temp.win-amd64-cpython-313\Release\httptools\parser
      creating build\temp.win-amd64-cpython-313\Release\vendor\llhttp\src
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\noelt-be\AppData\Local\Temp\pip-install-r_ebva0u\httptools_798f24adaa5e4abe9a61d02c99a97b30\vendor\llhttp\include -IC:\Users\noelt-be\AppData\Local\Temp\pip-install-r_ebva0u\httptools_798f24adaa5e4abe9a61d02c99a97b30\vendor\llhttp\src -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\include -IC:\Users\noelt-be\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tchttptools/parser/parser.c /Fobuild\temp.win-amd64-cpython-313\Release\httptools/parser/parser.obj -O2
      parser.c
      httptools/parser/parser.c(849): warning C4996: 'Py_UNICODE': deprecated in 3.13
      httptools/parser/parser.c(850): warning C4996: 'Py_UNICODE': deprecated in 3.13
      httptools/parser/parser.c(3531): warning C4090: "=": Unterschiedliche "const"-Qualifizierer
      httptools/parser/parser.c(9938): error C2198: "int _PyLong_AsByteArray(PyLongObject *,unsigned char *,size_t,int,int,int)": Nicht gen\x81gend Argumente f\x81r Aufruf.
      httptools/parser/parser.c(10134): error C2198: "int _PyLong_AsByteArray(PyLongObject *,unsigned char *,size_t,int,int,int)": Nicht gen\x81gend Argumente f\x81r Aufruf.
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
Successfully built strictdoc
Failed to build httptools
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (httptools)
```

**Comment by bernhard-tuvsud** [comment]
Switched back to python 12.9, Now it works. Thanks.
